spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/deliciousfood
    #username: root
    #password: 123456

    #线上阿里云数据库
    url: jdbc:mysql://rm-cn-g4t42nm7c00050ao.rwlb.rds.aliyuncs.com/deliciousfood
    username: lipangpang
    password: 1994xpp0805w@

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8
    default-property-inclusion: non_null

  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

  security:
    user:
      name: admin
      password: 123456

  data:
    redis:
      host: 116.205.106.116
      port: 6379
      password: 1994xpp0805w.


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.project.mapper


server:
  port: 8080


logging:
  level:
    org:
      mybatis: DEBUG
      example:
        mapper: DEBUG
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 配置 Sa-Token 使用 Redis 存储 Token
  data-type: redis

  is-read-cookie: true # 是否允许读取cookie中的token
  is-read-header: true

